// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_bilibili from "./routes/api/bilibili.tsx";
import * as $api_bilibili_bvid_ from "./routes/api/bilibili/[bvid].ts";
import * as $api_bilibili_proxyimg from "./routes/api/bilibili/proxyimg.ts";
import * as $api_countdown_slug_ from "./routes/api/countdown/[slug].ts";
import * as $api_firebasefood from "./routes/api/firebasefood.ts";
import * as $api_hello from "./routes/api/hello.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_youtube_channel_channelIds_ from "./routes/api/youtube/channel/[channelIds].ts";
import * as $api_youtube_videos_videoIds_ from "./routes/api/youtube/videos/[videoIds].ts";
import * as $bilibili from "./routes/bilibili.tsx";
import * as $blog_slug_ from "./routes/blog/[slug].tsx";
import * as $countdown from "./routes/countdown.tsx";
import * as $firebasefood from "./routes/firebasefood.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $youtube from "./routes/youtube.tsx";
import * as $BilibiliTable from "./islands/BilibiliTable.tsx";
import * as $CountdownTimer from "./islands/CountdownTimer.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $FirebaseFoodTable from "./islands/FirebaseFoodTable.tsx";
import * as $Nav from "./islands/Nav.tsx";
import * as $YouTubeTable from "./islands/YouTubeTable.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/bilibili.tsx": $api_bilibili,
    "./routes/api/bilibili/[bvid].ts": $api_bilibili_bvid_,
    "./routes/api/bilibili/proxyimg.ts": $api_bilibili_proxyimg,
    "./routes/api/countdown/[slug].ts": $api_countdown_slug_,
    "./routes/api/firebasefood.ts": $api_firebasefood,
    "./routes/api/hello.ts": $api_hello,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/youtube/channel/[channelIds].ts":
      $api_youtube_channel_channelIds_,
    "./routes/api/youtube/videos/[videoIds].ts": $api_youtube_videos_videoIds_,
    "./routes/bilibili.tsx": $bilibili,
    "./routes/blog/[slug].tsx": $blog_slug_,
    "./routes/countdown.tsx": $countdown,
    "./routes/firebasefood.tsx": $firebasefood,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/youtube.tsx": $youtube,
  },
  islands: {
    "./islands/BilibiliTable.tsx": $BilibiliTable,
    "./islands/CountdownTimer.tsx": $CountdownTimer,
    "./islands/Counter.tsx": $Counter,
    "./islands/FirebaseFoodTable.tsx": $FirebaseFoodTable,
    "./islands/Nav.tsx": $Nav,
    "./islands/YouTubeTable.tsx": $YouTubeTable,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
